### ISSUE TITLE
Vapoursynth + vmaf failing with master tip (Docker)

### ISSUE THREAD

**Issue by cogman** [rust-av/Av1an#266]
```
Traceback (most recent call last):
  File "/Av1an/av1an.py", line 6, in <module>
    main()
  File "/Av1an/cli/__main__.py", line 15, in main
    manager.run()
  File "/Av1an/av1an/manager/Manager.py", line 65, in run
    EncodingManager().encode_file(proj)
  File "/Av1an/av1an/manager/Manager.py", line 91, in encode_file
    split_locations = split_routine(project, project.resume)
  File "/Av1an/av1an/split.py", line 48, in split_routine
    scenes = calc_split_locations(project)
  File "/Av1an/av1an/split.py", line 196, in calc_split_locations
    sc = aom_keyframes(
  File "/Av1an/av1an/scenedetection/aom_kf.py", line 307, in aom_keyframes
    total = frame_probe_fast(video_path, is_vs)
  File "/Av1an/av1an/utils.py", line 58, in frame_probe_fast
    total = frame_probe(source)
  File "/Av1an/av1an/utils.py", line 71, in frame_probe
    return frame_probe_vspipe(source)
TypeError: argument 'source': 'PosixPath' object cannot be converted to 'PyString'
```

It looks like the object passed into `frame_probe_vspipe` is expected to be a string but is instead a python path, which makes rust sad.

**Comment by cogman** [comment]
Minimum reproduction

test.vpy
```
from vapoursynth import core

core.std.BlankClip().set_output()
```

Command I used

`docker run -v ${PWD}:/videos -it --rm masterofzen/av1an:latest -i test.vpy`

**Comment by shssoichiro** [comment]
This is a very old issue which predates the migration of Av1an to Rust. As such, this is likely to have been fixed during the Rust rewrite, or is no longer relevant.

If this issue is still relevant, please feel free to reopen this ticket. Thanks!
