### ISSUE TITLE
appveyor Failed

### ISSUE THREAD

**Issue by barti04** [rust-av/Av1an#291]
Failed building artifacts because storage is exceeded, which results in no artifact being available.

[log.txt](https://github.com/master-of-zen/Av1an/files/6797053/log.txt)
https://ci.appveyor.com/project/master-of-zen/av1an/build/artifacts

**Comment by master-of-zen** [comment]
Yes, installation should be done by pip or manually building current python/rust git

**Comment by barti04** [comment]
When trying to manually build I get the following error:

error: manifest path `Av1an-master\Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
error: cargo failed with code: 101
I only work with python so I'm pretty lost with rust.

**Comment by master-of-zen** [comment]
Follow this
https://gist.github.com/master-of-zen/0833bec1e7df72ed165083cd44e9187b

**Comment by barti04** [comment]
I did but when trying to run the last command "./av1an.py -i test.mp4 -l log.log" I got another error:
Traceback (most recent call last):
  File "C:\Users\DJ\Downloads\Av1an-master\av1an.py", line 4, in <module>
    from cli.__main__ import main
  File "C:\Users\DJ\Downloads\Av1an-master\cli\__main__.py", line 2, in <module>
    from av1an.arg_parse import Args
  File "C:\Users\DJ\Downloads\Av1an-master\av1an\__init__.py", line 2, in <module>
    from av1an_pyo3 import *
ModuleNotFoundError: No module named 'av1an_pyo3'

**Comment by master-of-zen** [comment]
you need to run it from venv that you used for compilation previously

**Comment by barti04** [comment]
I use Intelji Idea Ultimate doesn't it take care of it?

**Comment by master-of-zen** [comment]
I don't know, I use command line and create, compile, execute as said there https://gist.github.com/master-of-zen/0833bec1e7df72ed165083cd44e9187

**Comment by barti04** [comment]
Ok, thanks for your help I got it working.
Intelji Idea Commandline behavior seems strange the "python3 -m venv env" isn't working correctly, but when using the build-in Build and run functions it's working.

**Comment by master-of-zen** [comment]
@barti04 right now av1an is pure rust, so it should work just fine

**Comment by shssoichiro** [comment]
This is a very old issue which predates the migration of Av1an to Rust. As such, this is likely to have been fixed during the Rust rewrite, or is no longer relevant.

If this issue is still relevant, please feel free to reopen this ticket. Thanks!
